### ISSUE TITLE
how to get the client id and token

### ISSUE THREAD

**Issue by hashvg7** [manishgupta24/Paytm-Seller-API-Python#1]
Hi, Great work, but stuck at getting the client id and the token, can you kindly help on the same
thx

**Comment by manishgupta24** [comment]
You have to ask Paytm Seller Support and they will provide you the
credentials.

**Comment by hashvg7** [comment]
thx

sent from iphone, excuse typos




On Thu, Sep 1, 2016 at 2:03 PM +0530, "Manish Gupta" <notifications@github.com> wrote:










You have to ask Paytm Seller Support and they will provide you the

credentials.



On Thu, Sep 1, 2016 at 12:00 PM, harshad vg <notifications@github.com>

wrote:
